[[redirects]]
  from = "/*"
  to = "/nope.html"
  status = 302
  force = true
  query = {site = ":site"}
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false